{{- if .Values.serviceAccount.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "verify.serviceAccountName" . }}
  labels:
    {{- include "verify.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
