apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-data
  labels: {{ include "verify.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
      - env: {{ include "verify.dbUserPgEnv" . | nindent 16 }}
        name: deploy-data
        imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.api.pullPolicy }}
        image: {{ .Values.image.schema.repository }}:{{ default .Values.defaultImageTag .Values.image.schema.tag }}
      restartPolicy: Never
  backoffLimit: 4
