name: hackathon OTP

on:
  push:
    branches: [main, feat/build_pipeline]
  pull_request:
    branches: [main, feat/build_pipeline]


jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/bcgov/hackathon-otp
          tags: |
            type=sha,format=long,prefix=
            latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: api
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          file: api/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        